### ISSUE TITLE
Does not work with angular-cli

### ISSUE THREAD

**Issue by peteralbert** [zeit/now-issues#13]
I generated a barebone Angular2 app using the latest angular-cli@1.0.0-beta.11-webpack and tried to deploy it with now - but running into an error.

Here's the full code to reproduce the issue:

```
npm install -g angular-cli@1.0.0-beta.11-webpack
ng new ng-sample
cd ng-sample
npm install --save angular-cli@1.0.0-beta.11-webpack
ng init
now
```

This results in the following error message:

```
content.charCodeAt is not a function
```` 

Here is the link to the app: https://ng-sample-heemmtsdjo.now.sh/

**Comment by forivall** [comment]
This looks like a bug in angular-cli's require hook: https://github.com/angular/angular-cli/blob/master/lib/cli/index.js#L16 where readFileSync is returning a buffer, and Module._compile expects a string. I would file a bug with angular-cli.

**Comment by leo** [comment]
@forivall Correct!
