### ISSUE TITLE
Looks like some packages are not installed

### ISSUE THREAD

**Issue by gillchristian** [zeit/now-issues#6]
Hi! I'm having trouble deploying an express app with now.

This is my `package.json`
```json
{
  "name": "my-app",
  "main": "src/server.js",
  "scripts": {
    "now-build": "npm i",
    "now-start": "node src/server.js",
  },
  "dependencies": {
    "express": "^4.14.0"
  },
  "engines": {
    "node": ">=6"
  }
}
```

I don't need to run a build so my `now-build` was just `echo 'skiping the build :D'`. But `now-start` was throwing this error:

```sh
TypeError: express is not a function
```
Pointing to the second line of my `server.js` file
```js
const express = require('express')
const app = express()
```

For the moment it is working with `npm install` running twice, since I added it to the `now-build` script.

PS: `now` is awesome :ghost:

**Comment by nkzawa** [comment]
I can't reproduce it. Do you still experienced the problem ?
