### ISSUE TITLE
Files missing on deploy (worked previously)

### ISSUE THREAD

**Issue by ctrlplusb** [zeit/now-issues#7]
Can't seem to resolve files at times, even though they are not git ignored and my project has been successfully deployed previously to now.

Previously it was failing to resolve my webpack config builder:
https://react-universally-hjjlvsrdbh.now.sh/

I changed the import statements to explicitly include the `.js`, but now it is failing to resolve `package.json`... O_o
https://react-universally-rhennedaii.now.sh/

**Comment by ctrlplusb** [comment]
Deployed okay now with no code changes 

_scratches head_

**Comment by ctrlplusb** [comment]
If I delete old deployments do I regain the deployment for my monthly limit?

**Comment by nkzawa** [comment]
@ctrlplusb no, your monthly limit doesn't increase.

**Comment by nkzawa** [comment]
I think it was temporarily unstable and was solved now. Feel free to reopen if you experienced the problem again.
